remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: IP Las Vegas
email: jacob@iplasvegas.com
description: This site contains blog posts regarding intellectual property in Las Vegas and beyond. Additionally, this site functions as a live resume for Jacob Smith.
url: https://iplasvegas.github.io
twitter_username: IPLasVegas
github_username:  IPLasVegas

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
     values:
      layout: "default"

exclude: 
  -Gemfile
  -Gemfile.lock
